FROM piacc-latest-notebook

RUN pip install notebook; PySpice==1.5, klayout==0.30.2, gdstk==0.9.60, ngspice-tools==0.0.2, PyYAML>=5.3, cffi>=1.14 ,matplotlib>=3.2 ,numpy>=1.18 ,ply>=3.11, scipy>=1.4, matplotlib==3.10.3

WORKDIR /PIACC

# Default command
#CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
